### ISSUE TITLE
Compatibility with Moodle 4.1

### ISSUE THREAD

**Issue by LMachucaORT** [catalyst/moodle-webservice_restful#22] opened 2023-11-03 15:47 UTC
Hello, best regards.

I would like to know if you are going to make the compatibility with Moodle 4.1 and PHP 8.2.

**Comment by FFawzy** [comment] 2024-01-11 12:22
We are also having the same problem with Moodle 4.3.1 and PHP 8.2.
-- 
the plugin status is OK in Moodle.

but whenever you try to use any of the endpoints I get a 500 server error

**Comment by lemerv** [comment] 2024-01-15 05:04
Also keen to see compatibility with Moodle 4.1. Any plans to support it?

**Comment by golenkovm** [comment] 2024-01-15 09:18
Hi all,

As I can see the current version of the plugin works as expected in Moodle 4.1 + PHP 7.4. Plugin readme and plugin directory would need to be updated though https://moodle.org/plugins/webservice_restful/versions . Higher php and Moodle version would need some work I assume. To make this issue more specific could you please provide more details and traces on the errors that you have in your envs. If there is a chance to raise a PR with a patch that would be much appreciated.

Kind regards,
Misha

**Comment by lemerv** [comment] 2024-01-16 21:41
I’m interested in the plugin directory being updated to show that version 4.1 is supported. The reason being that it is sometimes required that the specific version be stated in order to get approval to use the plugin. Is this possible?

**Comment by PradyumnaKrishna** [comment] 2024-01-21 16:25
> We are also having the same problem with Moodle 4.3.1 and PHP 8.2.
> 
> -- the plugin status is OK in Moodle.
> 
> but whenever you try to use any of the endpoints I get a 500 server error

There is a major changes in external_api from moodle that breaks this plugin. This might be the cause:
https://github.com/catalyst/moodle-webservice_restful/blob/1d9884fd76eda70385895619e205341bf0f81b33/locallib.php#L287

Minor fix will fix this plugin. I am looking to submit a PR to fix this change if the maintainer allows.

**Comment by Indigita2024** [comment] 2024-04-30 13:37
Hello
we recently upgrade from moodle 4.1 to 4.2.5. 
the restful call doesn't show any results. We also identified the internal server error 500
Please advise on how to fix
thanks

**Comment by golenkovm** [comment] 2024-05-01 00:45
Hi @Indigita2024,

This is on our todo list and should be fixed soon. Please stay tuned.

Kind regards,
Misha

**Comment by Indigita2024** [comment] 2024-05-02 06:10
Dear Misha,

Thank you very much for your message.

Do you have already an idea on when it will be fixed?

Thank you
Andrea




[signature_338771938]<https://www.indigita.ch/>

Andrea Briganti
Director
Head of e-Learning

Indigita SA
Via Balestra 22B, CH 6900, Lugano
T. +41 78 637 84 94
***@***.******@***.***>


www.indigita.ch<https://www.indigita.ch/> | Follow us  ***@***.*** <https://www.linkedin.com/company/indigita-sa/?viewAsMember=true>


***@***.***

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking or any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.




Confidential

**Comment by golenkovm** [comment] 2024-05-02 12:14
Hi @Indigita2024,

I'd expect this to be fixed next week.

Kind regards,
Misha

**Comment by golenkovm** [comment] 2024-05-06 04:10
Hi everybody,

This should be resolved now. Please feel free to give it a try and let me know if you still have any issues. New branch for Moodle 4.2+: https://github.com/catalyst/moodle-webservice_restful/tree/MOODLE_402_STABLE

Kind regards,
Misha

**Closed** 2024-05-06 04:13 UTC

**Comment by Indigita2024** [comment] 2024-05-06 05:44
Dear Misha
Thank you so much for the update
I did a first test and it works. Thanks a lot and have a nice week.
Andrea



[signature_338771938]<https://www.indigita.ch/>

Andrea Briganti
Director
Head of e-Learning

Indigita SA
Via Balestra 22B, CH 6900, Lugano
T. +41 78 637 84 94
***@***.******@***.***>


www.indigita.ch<https://www.indigita.ch/> | Follow us  ***@***.*** <https://www.linkedin.com/company/indigita-sa/?viewAsMember=true>


***@***.***

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking or any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.




Confidential

**Comment by LMachucaORT** [comment] 2024-05-06 15:12
Hi, everyone.

I test with Moodle 4.4 and PHP 8.2 and work it works. 
Thanks, @golenkovm.
